### ISSUE TITLE
Please update node-gyp so it is not dependant on obsolete python2

### ISSUE THREAD

**Issue by J-u-n-o** [xanderfrangos/global-mouse-events#2]

**Comment by xanderfrangos** [comment]
v1.0.4 is out, using the latest version of `node-gyp`. 👍

**Comment by xanderfrangos** [comment]
Upon further review, the old version of `node-gyp` was compatible with Python 3.x. Python 2.x was never required.

**Comment by nullsaint** [comment]
Getting this issue on macos:

Error: Module did not self-register: '/Users/mddeloarhossain/Desktop/test-electron/node_modules/global-mouse-events/build/Release/global_mouse_events.node'.
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)
    at Module._extensions..node (node:internal/modules/cjs/loader:1343:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2214)
    at Module.load (node:internal/modules/cjs/loader:1098:32)
    at Module._load (node:internal/modules/cjs/loader:945:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at Module.require (node:internal/modules/cjs/loader:1122:19)
    at require (node:internal/modules/helpers:130:18)
    at bindings (/Users/mddeloarhossain/Desktop/test-electron/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Users/mddeloarhossain/Desktop/test-electron/node_modules/global-mouse-events/index.js:3:34)
